#Create a copy of this file and name is config.yml
repo:
  key: #your personal access token
  domain: #your repo name ending with a tld (.dk .io .com etc)
  sourcePrivate: #true of false surrounded by ''
  stagePrivate: #true of false surrounded by ''
  prodPrivate: #true of false surrounded by ''
  user: #the GitHub user you are logged in as. This is needed to clone the source repo you are making
  email: #your email
  path: #/path/to/store/your/cloned/repos
  templateUser: #GitHubUser
  templateName: #GitHubRepo
  themeUser: #GitHubUser
  themeName: #GitHubRepo
