#Rename this file to config.yml or rename it to config.ym
repo:
  key: #your personal access token (one time use)
  domain: #your repo name ending with a tld (.dk .io .com etc)
  sourcePrivate: #true of false surrounded by ''
  stagePrivate: #true of false surrounded by ''
  prodPrivate: #true of false surrounded by ''
  user: #the GitHub user you are logged in as. This is needed to clone the source repo you are making
  email: #your email for circle ci
  path: /app #/path/to/store/your/cloned/repos
  templateUser: #GitHubUser
  templateName: #GitHubRepo
  theme: #true or false. No ''
  themeUser: #GitHubUser
  themeName: #GitHubRepo
  circle: #true or false. No ''. This will still edit the config files but not add or build the project on circle ci
  citoken: #your circle ci token. Leave empty if you desire to do this step manually
  cienvname: PHLOW_GHTOKEN #your circle ci environment name ussually PHLOW_GHTOKEN
  htmlproofer: #true or false. No ''