#Create a copy of this file and name it config.yml
repo:
  key: #your personal access token (one time use)
  domain: #your repo name ending with a tld (.dk .io .com etc)
  sourcePrivate: #true of false surrounded by ''
  stagePrivate: #true of false surrounded by ''
  prodPrivate: #true of false surrounded by ''
  user: #the GitHub user you are logged in as. This is needed to clone the source repo you are making
  email: #your email for circle ci
  path: #/path/to/store/your/cloned/repos
  templateUser: #GitHubUser
  templateName: #GitHubRepo
  themeUser: #GitHubUser
  themeName: #GitHubRepo
  citoken: #your circle ci token. Leave empty if you desire to do this step manually
  cienvname: #your circle ci environment name ussually PHLOW_GHTOKEN
